### ISSUE TITLE
Cannot complete steps in README

### ISSUE THREAD

**Issue by casey-SK** [beef331/picotemplate#1]
I was able to successfully download the Pico SDK. Them, when I run the command  ` nimble make ` i get the following error:

`Error: Specified directory (.../picotemplate/csource/build) does not contain a .nimble file.`

Okay, so there was a nimble file in the parent folder. If I run 'nimble make' from there I get the following error:

`Error: cannot open file: picostdlib`

So I then went to your other repository (https://github.com/beef331/picostdlib), copied the contents of the `src` folder into this projects `src` folder and the nimble make command successfully executed. 

Then when trying `nimble listen` I got the following error:

`Error: unhandled exception: FAILED: sudo minicom -b 115200 -o -D /dev/ttyACM0 [OSError]`

I decided to try a simpler program rand replaced the contents of `pico_nim.nim` with that of `blink.nim`. The blink program ran successfully.  

Thank you for making these bindings! Much appreciated. Just took a bit of troubleshoot to figure it out.

**Comment by beef331** [comment]
Seems like you forgot to do `niimble install --depsonly` from the projects root.

**Comment by beef331** [comment]
Commit: 31a4e74df2b50132a9a321c89fcb6e90a26fc10c resolves this by adding `nimble setup`

**Comment by casey-SK** [comment]
Thanks! Sorry I didn't follow the instructions fully. I see you have added an extra check for simple users like me haha. After my exams I am gonna play around with this some more. Maybe once I get a grip on it, I can contribute some documentation.

**Comment by casey-SK** [comment]
In case anyone runs into this issue:

`Error: unhandled exception: FAILED: sudo minicom -b 115200 -o -D /dev/ttyACM0 [OSError]`

You could be a simpleton like me and not have minicom installed on your system. install it with your package manager. Ubuntu:

`apt install minicom`

for the really novice users, maybe you could mention it as a dependency in your readme?

**Comment by beef331** [comment]
Read me has been updated thanks for finding issues with the docs :smile:
